INSERT INTO ccn (Numero_Fiche,Ccn_1_Numero,Ccn_1_Libelle,Ccn_2_Numero,Ccn_2_Libelle,Ccn_3_Numero,Ccn_3_Libelle) VALUES

('RNCP286','3246','Animation socioculturelle','','','',''),
('RNCP1396','3255','Cabinets dentaires','','','',''),
('RNCP1404','3611','Personnel des organismes de contrôle laitier','','','',''),
('RNCP1448','3104','Industrie pharmaceutique','','','',''),
('RNCP1465','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP1472','3150','Photographie professionnelle','','','',''),
('RNCP1473','3224','Détaillants et détaillants-fabricants en confiserie, chocolaterie et biscuiterie','','','',''),
('RNCP1475','3010','Fleuristes, vente et services des animaux familiers','','','',''),
('RNCP1476','3131','Entreprises de commerce, de location et de réparation de tracteurs, machines et matériels agricoles, de matériels de travaux publics, de bâtiment et de manutention, de matériels de motoculture de plaisance, de jardins et d''espaces verts','','','',''),
('RNCP1490','3101','Boucherie, boucherie-charcuterie et boucherie hippophagique.Commerces de détail de boucherie','','','',''),
('RNCP1544','3107','Bâtiment et travaux publics','','','',''),
('RNCP1675','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP1982','3243','Poissonnerie (Commerce de détail, gros et demi-gros)','','','',''),
('RNCP2323','3104','Industrie pharmaceutique','','','',''),
('RNCP2847','3180','Salariés du particulier employeur','','','',''),
('RNCP2848','3180','Salariés du particulier employeur','','','',''),
('RNCP4072','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP4073','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP4074','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP4075','3603','Centres équestres','','','',''),
('RNCP4076','3049','Commerce des articles de sport et d''équipements de loisirs','','','',''),
('RNCP4077','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP4078','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP4079','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP4080','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP4081','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP4228','','','3108','Industries chimiques et connexes','',''),
('RNCP4456','3616','Coopératives agricoles de cérales, de meunerie, d''approvisionnement, d''alimentation du bétail et d''oléagineux','','','',''),
('RNCP4535','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP4536','3101','Boucherie, boucherie-charcuterie et boucherie hippophagique.Commerces de détail de boucherie','','','',''),
('RNCP4631','3076','Commerces et services de l''audiovisuel, de l''électronique et de l''équipement ménager','','','',''),
('RNCP4633','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP4687','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP4742','3029','Vins, cidres, jus de fruits, sirops, spiritueux et liqueurs de France','','','',''),
('RNCP5392','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP5396','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5397','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5443','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5444','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5476','3300','Mutualité','','','',''),
('RNCP5477','3300','Mutualité','','','',''),
('RNCP5478','3300','Mutualité','','','',''),
('RNCP5485','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5486','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5487','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5488','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5489','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5490','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5491','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5492','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5493','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5494','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5495','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5496','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP5541','3238','Industries céramiques de France','','','',''),
('RNCP5555','3196','Entreprises de prévention et de sécurité','','','',''),
('RNCP5556','3168','Personnel des cabinets médicaux','','','',''),
('RNCP5594','3109','Métallurgie','','','',''),
('RNCP5718','3107','Bâtiment et travaux publics','','','',''),
('RNCP5733','','','3301','Personnel des prestataires de services dans le domaine du secteur tertiaire','',''),
('RNCP5749','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP5750','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP5751','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP5752','3001','Industrie du pétrole','','','',''),
('RNCP5753','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP5984','3196','Entreprises de prévention et de sécurité','','','',''),
('RNCP5985','3196','Entreprises de prévention et de sécurité','','','',''),
('RNCP5996','','','','','3063','Fabrication et commerce des produits à  usage pharmaceutique, parapharmaceutique et vétérinaire'),
('RNCP6013','3073','Entreprises de la publicité et assimilées','','','',''),
('RNCP6031','3328','Sport','','','',''),
('RNCP6032','3328','Sport','','','',''),
('RNCP6033','3328','Sport','','','',''),
('RNCP6034','3328','Sport','','','',''),
('RNCP6035','3328','Sport','','','',''),
('RNCP6036','3107','Bâtiment et travaux publics','','','',''),
('RNCP6037','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP6038','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP6039','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP6040','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP6041','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP6042','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP6043','3328','Sport','','','',''),
('RNCP6091','3121','Entrepositaires-grossistes en boissons','','','',''),
('RNCP6092','3121','Entrepositaires-grossistes en boissons','','','',''),
('RNCP6093','3121','Entrepositaires-grossistes en boissons','','','',''),
('RNCP6094','3121','Entrepositaires-grossistes en boissons','','','',''),
('RNCP6095','3249','Organismes de formation','','','',''),
('RNCP6248','3107','Bâtiment et travaux publics','','','',''),
('RNCP6253','3159','Coiffure','','','',''),
('RNCP6261','3617','Entreprises du paysage (Salariés non cadres)','','','',''),
('RNCP6262','3273','Manutention portuaire','','','',''),
('RNCP6587','3273','Manutention portuaire','','','',''),
('RNCP6588','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP6589','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP6590','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP6591','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP6592','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP6593','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP6594','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP6595','3265','Sociétés d''assurances','','','',''),
('RNCP6596','3272','Jardineries et graineteries','','','',''),
('RNCP6597','3272','Jardineries et graineteries','','','',''),
('RNCP6598','3328','Sport','','','',''),
('RNCP6599','3328','Sport','','','',''),
('RNCP6900','3224','Détaillants et détaillants-fabricants en confiserie, chocolaterie et biscuiterie','','','',''),
('RNCP6901','3215','Pâtisserie','','','',''),
('RNCP6904','3131','Entreprises de commerce, de location et de réparation de tracteurs, machines et matériels agricoles, de matériels de travaux publics, de bâtiment et de manutention, de matériels de motoculture de plaisance, de jardins et d''espaces verts','','','',''),
('RNCP6970','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP6971','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP6976','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP6977','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP6978','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP6979','3273','Manutention portuaire','','','',''),
('RNCP6980','3273','Manutention portuaire','','','',''),
('RNCP6995','3328','Sport','','','',''),
('RNCP6997','3328','Sport','','','',''),
('RNCP7419','3010','Fleuristes, vente et services des animaux familiers','','','',''),
('RNCP7448','3107','Bâtiment et travaux publics','','','',''),
('RNCP7449','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7450','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7451','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7452','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7453','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7454','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7455','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP7456','3273','Manutention portuaire','','','',''),
('RNCP7457','3273','Manutention portuaire','','','',''),
('RNCP7458','3328','Sport','','','',''),
('RNCP9054','3604','Caves coopératives vinicoles et leurs unions','','','',''),
('RNCP9084','3215','Pâtisserie','','','',''),
('RNCP9105','3008','Détaillants en chaussure','','','',''),
('RNCP9106','','','3225','Personnel des entreprises de restauration de collectivités','',''),
('RNCP9107','','','3225','Personnel des entreprises de restauration de collectivités','',''),
('RNCP9108','','','3225','Personnel des entreprises de restauration de collectivités','',''),
('RNCP9109','3328','Sport','','','',''),
('RNCP9110','3328','Sport','','','',''),
('RNCP9373','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP9386','3173','Entreprises de propreté','','','',''),
('RNCP9387','3173','Entreprises de propreté','','','',''),
('RNCP9388','3173','Entreprises de propreté','','','',''),
('RNCP9412','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP9413','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP9414','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP9415','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP9416','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP9417','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP9673','3104','Industrie pharmaceutique','','','',''),
('RNCP9812','3155','Fabrication de l''ameublement','','','',''),
('RNCP9824','3117','Boulangerie-pâtisserie (Entreprises artisanales)','','','',''),
('RNCP9876','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP9877','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9879','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9880','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9881','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9898','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9899','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9900','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9901','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9902','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9903','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9905','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP9906','3328','Sport','','','',''),
('RNCP11502','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP11562','3603','Centres équestres','','','',''),
('RNCP11563','3173','Entreprises de propreté','','','',''),
('RNCP11566','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP11567','3173','Entreprises de propreté','','','',''),
('RNCP11571','3173','Entreprises de propreté','','','',''),
('RNCP11891','','','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP12050','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP12051','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP12052','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP12053','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP12054','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP12055','3167','Personnel des jeux dans les casinos','','','',''),
('RNCP12056','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP12057','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP12070','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP12071','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP12072','3049','Commerce des articles de sport et d''équipements de loisirs','','','',''),
('RNCP12110','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP12111','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP12202','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP12204','3603','Centres équestres','','','',''),
('RNCP12274','3269','Pompes funèbres','','','',''),
('RNCP12275','3328','Sport','','','',''),
('RNCP12306','3123','Parfumerie - Esthétique','','','',''),
('RNCP12351','3167','Personnel des jeux dans les casinos','','','',''),
('RNCP12361','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP12362','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP12363','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP12381','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP12382','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP12383','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP12418','3173','Entreprises de propreté','','','',''),
('RNCP12836','3042','Thermiques (Equipements)','','','',''),
('RNCP13086','3328','Sport','','','',''),
('RNCP13094','3298','Thermalisme','','','',''),
('RNCP13133','3300','Mutualité','','','',''),
('RNCP13397','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP13398','3246','Animation socioculturelle','','','',''),
('RNCP13586','3107','Bâtiment et travaux publics','','','',''),
('RNCP13608','3133','Charcuterie de détail','','','',''),
('RNCP13609','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP13610','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP13611','3328','Sport','','','',''),
('RNCP13612','3328','Sport','','','',''),
('RNCP13613','3328','Sport','','','',''),
('RNCP13638','3603','Centres équestres','','','',''),
('RNCP13711','3328','Sport','','','',''),
('RNCP13712','3328','Sport','','','',''),
('RNCP13713','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP13714','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP13715','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP13881','3328','Sport','','','',''),
('RNCP14227','3056','Ameublement','','','',''),
('RNCP14307','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP14422','3010','Fleuristes, vente et services des animaux familiers','','','',''),
('RNCP14544','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP14545','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP14546','3328','Sport','','','',''),
('RNCP14547','3251','Commerces de détail non alimentaires','','','',''),
('RNCP14637','3123','Parfumerie - Esthétique','','','',''),
('RNCP14638','3123','Parfumerie - Esthétique','','','',''),
('RNCP14876','3328','Sport','','','',''),
('RNCP14877','3328','Sport','','','',''),
('RNCP14881','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP14907','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP15075','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP15076','3117','Boulangerie-pâtisserie (Entreprises artisanales)','','','',''),
('RNCP15277','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP15278','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15280','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15281','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15282','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15283','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15285','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP15287','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP15720','3328','Sport','','','',''),
('RNCP15807','3046','Caoutchouc','','','',''),
('RNCP15809','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP15810','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP15811','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP15814','','','2642','Production audiovisuelle ','',''),
('RNCP15823','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15845','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP15846','3046','Caoutchouc','','','',''),
('RNCP15847','3046','Caoutchouc','','','',''),
('RNCP15851','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP15967','3328','Sport','','','',''),
('RNCP16070','3328','Sport','','','',''),
('RNCP16071','3328','Sport','','','',''),
('RNCP16220','3614','Coopératives agricoles, unions de coopératives agricoles et sica de fleurs, de fruits et légumes et de pommes de terre','','','',''),
('RNCP16221','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP16222','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP16223','','','3098','Industries de l''habillement','',''),
('RNCP16263','3106','Industrie textile','','','',''),
('RNCP16264','','','3098','Industries de l''habillement','',''),
('RNCP16265','3106','Industrie textile','','','',''),
('RNCP16266','3163','Industrie de la chaussure et des articles chaussants','','','',''),
('RNCP16267','3163','Industrie de la chaussure et des articles chaussants','','','',''),
('RNCP16268','3163','Industrie de la chaussure et des articles chaussants','','','',''),
('RNCP16269','3163','Industrie de la chaussure et des articles chaussants','','','',''),
('RNCP16270','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP16271','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP16272','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP16273','3074','Blanchisserie, laverie, location de linge, nettoyage à  sec, pressing et teinturerie','','','',''),
('RNCP16329','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP16456','3044','Commerces de gros','','','',''),
('RNCP16457','3044','Commerces de gros','','','',''),
('RNCP16458','3044','Commerces de gros','','','',''),
('RNCP16580','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP16645','3108','Industries chimiques et connexes','','','',''),
('RNCP16646','3328','Sport','','','',''),
('RNCP16647','3328','Sport','','','',''),
('RNCP16686','3328','Sport','','','',''),
('RNCP16962','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP17211','3107','Bâtiment et travaux publics','','','',''),
('RNCP17293','3108','Industries chimiques et connexes','','','',''),
('RNCP17294','3108','Industries chimiques et connexes','','','',''),
('RNCP17295','3108','Industries chimiques et connexes','','','',''),
('RNCP17296','3108','Industries chimiques et connexes','','','',''),
('RNCP17297','3108','Industries chimiques et connexes','','','',''),
('RNCP17299','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP17300','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP17302','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP17303','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP17313','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP17314','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP17332','3328','Sport','','','',''),
('RNCP17333','3328','Sport','','','',''),
('RNCP17335','3328','Sport','','','',''),
('RNCP17336','3328','Sport','','','',''),
('RNCP17675','3617','Entreprises du paysage (Salariés non cadres)','','','',''),
('RNCP17677','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP17841','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP17844','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP18119','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP18130','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP18136','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP18211','3106','Industrie textile','','','',''),
('RNCP18214','','','','','3163','Industrie de la chaussure et des articles chaussants'),
('RNCP18215','3106','Industrie textile','','','',''),
('RNCP18216','','','3098','Industries de l''habillement','',''),
('RNCP18224','','','','','3058','Industrie des cuirs et peaux'),
('RNCP18225','3106','Industrie textile','','','',''),
('RNCP18226','3106','Industrie textile','','','',''),
('RNCP18228','','','3098','Industries de l''habillement','',''),
('RNCP18229','','','','','3157','Industries de la maroquinerie, articles de voyage, chasse-sellerie, bracelets en cuir'),
('RNCP18230','3167','Personnel des jeux dans les casinos','','','',''),
('RNCP18231','3159','Coiffure','','','',''),
('RNCP18302','3276','Personnel des institutions de retraites complémentaires','','','',''),
('RNCP18610','','','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP19165','3015','Cordonnerie','','','',''),
('RNCP19166','3109','Métallurgie','','','',''),
('RNCP19184','3101','Boucherie, boucherie-charcuterie et boucherie hippophagique.Commerces de détail de boucherie','','','',''),
('RNCP19230','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP19248','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP19249','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP19250','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP19355','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP19421','','','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP19452','3109','Métallurgie','','','',''),
('RNCP19454','3603','Centres équestres','','','',''),
('RNCP19456','3109','Métallurgie','','','',''),
('RNCP19457','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP19458','3109','Métallurgie','','','',''),
('RNCP19459','3109','Métallurgie','','','',''),
('RNCP19460','3109','Métallurgie','','','',''),
('RNCP19468','3117','Boulangerie-pâtisserie (Entreprises artisanales)','','','',''),
('RNCP20256','3150','Photographie professionnelle','','','',''),
('RNCP20270','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP20271','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP20608','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP20609','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP20611','3029','Vins, cidres, jus de fruits, sirops, spiritueux et liqueurs de France','','','',''),
('RNCP20613','3226','Entreprises artistiques et culturelles','','','',''),
('RNCP20614','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP20617','','','3225','Personnel des entreprises de restauration de collectivités','',''),
('RNCP20618','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP20621','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP20624','3328','Sport','','','',''),
('RNCP20627','3328','Sport','','','',''),
('RNCP20661','3242','Production des papiers-cartons et celluloses (OETAM)','','','',''),
('RNCP20664','3242','Production des papiers-cartons et celluloses (OETAM)','','','',''),
('RNCP20666','3242','Production des papiers-cartons et celluloses (OETAM)','','','',''),
('RNCP20667','3135','Industries de cartonnage','','','',''),
('RNCP21570','3049','Commerce des articles de sport et d''équipements de loisirs','','','',''),
('RNCP21641','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP21801','3109','Métallurgie','','','',''),
('RNCP21804','3109','Métallurgie','','','',''),
('RNCP21805','3109','Métallurgie','','','',''),
('RNCP21815','3157','Industries de la maroquinerie, articles de voyage, chasse-sellerie, bracelets en cuir','','','',''),
('RNCP21816','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP21817','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP21818','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP21819','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP21820','3109','Métallurgie','','','',''),
('RNCP22065','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP22070','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP22072','3066','Plasturgie','','','',''),
('RNCP22073','3066','Plasturgie','','','',''),
('RNCP22074','3066','Plasturgie','','','',''),
('RNCP22075','3066','Plasturgie','','','',''),
('RNCP22077','3066','Plasturgie','','','',''),
('RNCP22078','3066','Plasturgie','','','',''),
('RNCP22079','3066','Plasturgie','','','',''),
('RNCP22080','3066','Plasturgie','','','',''),
('RNCP22081','3066','Plasturgie','','','',''),
('RNCP22100','3249','Organismes de formation','','','',''),
('RNCP22112','3133','Charcuterie de détail','','','',''),
('RNCP22312','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP22961','3107','Bâtiment et travaux publics','','','',''),
('RNCP23021','3109','Métallurgie','','','',''),
('RNCP23022','3109','Métallurgie','','','',''),
('RNCP23023','3109','Métallurgie','','','',''),
('RNCP23024','3109','Métallurgie','','','',''),
('RNCP23025','3271','Hôtellerie de plein air','','','',''),
('RNCP23026','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP23027','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP23028','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP23057','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP23058','3104','Industrie pharmaceutique','','','',''),
('RNCP23059','3104','Industrie pharmaceutique','','','',''),
('RNCP23060','3104','Industrie pharmaceutique','','','',''),
('RNCP23061','3104','Industrie pharmaceutique','','','',''),
('RNCP23062','3104','Industrie pharmaceutique','','','',''),
('RNCP23063','3104','Industrie pharmaceutique','','','',''),
('RNCP23064','3104','Industrie pharmaceutique','','','',''),
('RNCP23067','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP23068','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP23069','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP23072','3167','Personnel des jeux dans les casinos','','','',''),
('RNCP23073','3328','Sport','','','',''),
('RNCP23074','3328','Sport','','','',''),
('RNCP23653','3155','Fabrication de l''ameublement','','','',''),
('RNCP23705','','','2717','Entreprises techniques au service de la création et de l''évènement ','',''),
('RNCP23706','2642','Production audiovisuelle ','','','',''),
('RNCP23707','2642','Production audiovisuelle ','','','',''),
('RNCP23708','3255','Cabinets dentaires','','','',''),
('RNCP23709','3229','Enseignement privé','','','',''),
('RNCP23710','3249','Organismes de formation','','','',''),
('RNCP23711','3328','Sport','','','',''),
('RNCP23712','3328','Sport','','','',''),
('RNCP23713','3144','Gardiens, concierges et employés d''immeubles','','','',''),
('RNCP24884','','','3109','Métallurgie','',''),
('RNCP24885','3109','Métallurgie','','','',''),
('RNCP24886','','','3608','Coopératives agricoles laitières','',''),
('RNCP24887','','','3608','Coopératives agricoles laitières','',''),
('RNCP24888','','','3608','Coopératives agricoles laitières','',''),
('RNCP24889','3124','Industrie laitière','','','',''),
('RNCP24890','','','3608','Coopératives agricoles laitières','',''),
('RNCP24891','','','3608','Coopératives agricoles laitières','',''),
('RNCP24892','','','3608','Coopératives agricoles laitières','',''),
('RNCP24893','3124','Industrie laitière','','','',''),
('RNCP24894','','','3608','Coopératives agricoles laitières','',''),
('RNCP24895','3109','Métallurgie','','','',''),
('RNCP24896','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP24898','3328','Sport','','','',''),
('RNCP24899','3328','Sport','','','',''),
('RNCP25560','3187','Entreprises relevant de la navigation de plaisance','','','',''),
('RNCP25561','3187','Entreprises relevant de la navigation de plaisance','','','',''),
('RNCP25562','3187','Entreprises relevant de la navigation de plaisance','','','',''),
('RNCP25563','3187','Entreprises relevant de la navigation de plaisance','','','',''),
('RNCP25564','3187','Entreprises relevant de la navigation de plaisance','','','',''),
('RNCP25594','3104','Industrie pharmaceutique','','','',''),
('RNCP25597','3104','Industrie pharmaceutique','','','',''),
('RNCP25598','3104','Industrie pharmaceutique','','','',''),
('RNCP25599','3104','Industrie pharmaceutique','','','',''),
('RNCP25600','3104','Industrie pharmaceutique','','','',''),
('RNCP26287','3300','Mutualité','','','',''),
('RNCP26288','3300','Mutualité','','','',''),
('RNCP26289','3300','Mutualité','','','',''),
('RNCP26291','3301','Personnel des prestataires de services dans le domaine du secteur tertiaire','','','',''),
('RNCP26293','3092','Industries alimentaires diverses','','','',''),
('RNCP26294','3108','Industries chimiques et connexes','','','',''),
('RNCP26295','3108','Industries chimiques et connexes','','','',''),
('RNCP26296','3108','Industries chimiques et connexes','','','',''),
('RNCP26297','3108','Industries chimiques et connexes','','','',''),
('RNCP26300','3108','Industries chimiques et connexes','','','',''),
('RNCP26301','3131','Entreprises de commerce, de location et de réparation de tracteurs, machines et matériels agricoles, de matériels de travaux publics, de bâtiment et de manutention, de matériels de motoculture de plaisance, de jardins et d''espaces verts','','','',''),
('RNCP26309','3108','Industries chimiques et connexes','','','',''),
('RNCP26310','3108','Industries chimiques et connexes','','','',''),
('RNCP26312','3300','Mutualité','','','',''),
('RNCP26314','3301','Personnel des prestataires de services dans le domaine du secteur tertiaire','','','',''),
('RNCP26316','3301','Personnel des prestataires de services dans le domaine du secteur tertiaire','','','',''),
('RNCP26322','3328','Sport','','','',''),
('RNCP26333','3328','Sport','','','',''),
('RNCP26596','3102','Boulangerie pâtisserie industrielle','','','',''),
('RNCP26598','3102','Boulangerie pâtisserie industrielle','','','',''),
('RNCP26599','3102','Boulangerie pâtisserie industrielle','','','',''),
('RNCP26838','2717','Entreprises techniques au service de la création et de l''évènement ','','','',''),
('RNCP26846','3618','Convention collective nationale de la conchyliculture','','','',''),
('RNCP26847','3618','Convention collective nationale de la conchyliculture','','','',''),
('RNCP26848','3051','Bijouterie, joaillerie, orfèvrerie et activités qui s''y rattachent','','','',''),
('RNCP26849','3051','Bijouterie, joaillerie, orfèvrerie et activités qui s''y rattachent','','','',''),
('RNCP26850','3051','Bijouterie, joaillerie, orfèvrerie et activités qui s''y rattachent','','','',''),
('RNCP26851','3051','Bijouterie, joaillerie, orfèvrerie et activités qui s''y rattachent','','','',''),
('RNCP26852','3051','Bijouterie, joaillerie, orfèvrerie et activités qui s''y rattachent','','','',''),
('RNCP26853','3050','Miroiterie, transformation et négoce du verre','','','',''),
('RNCP26855','3050','Miroiterie, transformation et négoce du verre','','','',''),
('RNCP27062','','','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','',''),
('RNCP27063','3106','Industrie textile','','','',''),
('RNCP27064','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP27065','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP27104','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP27322','3328','Sport','','','',''),
('RNCP27323','3328','Sport','','','',''),
('RNCP27324','3107','Bâtiment et travaux publics','','','',''),
('RNCP27381','3108','Industries chimiques et connexes','','','',''),
('RNCP27382','3086','Industries des tuiles et briques','','','',''),
('RNCP27383','3086','Industries des tuiles et briques','','','',''),
('RNCP27384','3086','Industries des tuiles et briques','','','',''),
('RNCP27385','3273','Manutention portuaire','','','',''),
('RNCP27387','2372','Distribution directe','','','',''),
('RNCP27388','3076','Commerces et services de l''audiovisuel, de l''électronique et de l''équipement ménager','','','',''),
('RNCP27412','3105','Régies de quartier','','','',''),
('RNCP27414','3254','Prothésistes dentaires et personnels de laboratoires de prothèses dentaires','','','',''),
('RNCP27533','3275','Espaces, de loisirs, d''attractions et culturels','','','',''),
('RNCP27847','3238','Industries céramiques de France','','','',''),
('RNCP27853','3238','Industries céramiques de France','','','',''),
('RNCP27854','3238','Industries céramiques de France','','','',''),
('RNCP27855','3238','Industries céramiques de France','','','',''),
('RNCP27856','3238','Industries céramiques de France','','','',''),
('RNCP27857','3238','Industries céramiques de France','','','',''),
('RNCP27858','3238','Industries céramiques de France','','','',''),
('RNCP27860','3275','Espaces, de loisirs, d''attractions et culturels','','','',''),
('RNCP27861','3275','Espaces, de loisirs, d''attractions et culturels','','','',''),
('RNCP27862','3275','Espaces, de loisirs, d''attractions et culturels','','','',''),
('RNCP27864','3328','Sport','','','',''),
('RNCP27906','3256','Mareyeurs-expéditeurs','','','',''),
('RNCP28199','3298','Thermalisme','','','',''),
('RNCP28228','3109','Métallurgie','','','',''),
('RNCP28229','3109','Métallurgie','','','',''),
('RNCP28230','3109','Métallurgie','','','',''),
('RNCP28231','3228','Industries et commerces de la récupération','','','',''),
('RNCP28232','3109','Métallurgie','','','',''),
('RNCP28233','3109','Métallurgie','','','',''),
('RNCP28234','3109','Métallurgie','','','',''),
('RNCP28235','3109','Métallurgie','','','',''),
('RNCP28236','3109','Métallurgie','','','',''),
('RNCP28237','3228','Industries et commerces de la récupération','','','',''),
('RNCP28238','3228','Industries et commerces de la récupération','','','',''),
('RNCP28239','3109','Métallurgie','','','',''),
('RNCP28240','3109','Métallurgie','','','',''),
('RNCP28241','3109','Métallurgie','','','',''),
('RNCP28242','3109','Métallurgie','','','',''),
('RNCP28243','3109','Métallurgie','','','',''),
('RNCP28244','3109','Métallurgie','','','',''),
('RNCP28245','3109','Métallurgie','','','',''),
('RNCP28246','3109','Métallurgie','','','',''),
('RNCP28247','3109','Métallurgie','','','',''),
('RNCP28248','3109','Métallurgie','','','',''),
('RNCP28249','3228','Industries et commerces de la récupération','','','',''),
('RNCP28250','3228','Industries et commerces de la récupération','','','',''),
('RNCP28342','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP28343','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP28344','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP28722','3157','Industries de la maroquinerie, articles de voyage, chasse-sellerie, bracelets en cuir','','','',''),
('RNCP28723','3279','Sociétés d''assistance','','','',''),
('RNCP28724','3249','Organismes de formation','','','',''),
('RNCP28725','3246','Animation socioculturelle','','','',''),
('RNCP28778','3616','Coopératives agricoles de cérales, de meunerie, d''approvisionnement, d''alimentation du bétail et d''oléagineux','','','',''),
('RNCP28779','3616','Coopératives agricoles de cérales, de meunerie, d''approvisionnement, d''alimentation du bétail et d''oléagineux','','','',''),
('RNCP28780','3102','Boulangerie pâtisserie industrielle','','','',''),
('RNCP28781','','','3026','Sucreries, sucreries-distilleries et raffineries de sucre','',''),
('RNCP28782','3060','Meunerie','','','',''),
('RNCP28783','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP28784','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP28785','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP28786','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP28787','','','','','3102','Boulangerie pâtisserie industrielle'),
('RNCP28789','','','3060','Meunerie','',''),
('RNCP28791','','','','','3102','Boulangerie pâtisserie industrielle'),
('RNCP28792','','','3060','Meunerie','',''),
('RNCP28793','','','3060','Meunerie','',''),
('RNCP28794','','','','','3102','Boulangerie pâtisserie industrielle'),
('RNCP28795','','','3060','Meunerie','',''),
('RNCP28796','','','3060','Meunerie','',''),
('RNCP28797','3328','Sport','','','',''),
('RNCP28800','3123','Parfumerie - Esthétique','','','',''),
('RNCP28801','','','','','3102','Boulangerie pâtisserie industrielle'),
('RNCP28802','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP28803','3063','Fabrication et commerce des produits à  usage pharmaceutique, parapharmaceutique et vétérinaire','','','',''),
('RNCP28804','3026','Sucreries, sucreries-distilleries et raffineries de sucre','','','',''),
('RNCP28805','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP28952','3328','Sport','','','',''),
('RNCP29210','','','','','3102','Boulangerie pâtisserie industrielle'),
('RNCP29213','','','','','3102','Boulangerie pâtisserie industrielle'),
('RNCP29387','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP29427','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP29464','3029','Vins, cidres, jus de fruits, sirops, spiritueux et liqueurs de France','','','',''),
('RNCP29465','3017','Convention Collective Nationale Unifiée Ports et Manutention -  IDCC','','','',''),
('RNCP29466','3017','Convention Collective Nationale Unifiée Ports et Manutention -  IDCC','','','',''),
('RNCP29468','3106','Industrie textile','','','',''),
('RNCP29469','','','3098','Industries de l''habillement','',''),
('RNCP29470','','','3098','Industries de l''habillement','',''),
('RNCP29471','','','3106','Industrie textile','',''),
('RNCP29472','3100','Entreprises de commission, de courtage et de commerce intracommunautaire et d''importation-exportation de France métropolitaine (CCNIE)','','','',''),
('RNCP29473','3100','Entreprises de commission, de courtage et de commerce intracommunautaire et d''importation-exportation de France métropolitaine (CCNIE)','','','',''),
('RNCP29474','3100','Entreprises de commission, de courtage et de commerce intracommunautaire et d''importation-exportation de France métropolitaine (CCNIE)','','','',''),
('RNCP29475','3010','Fleuristes, vente et services des animaux familiers','','','',''),
('RNCP29476','','','','','3215','Pâtisserie'),
('RNCP29477','3131','Entreprises de commerce, de location et de réparation de tracteurs, machines et matériels agricoles, de matériels de travaux publics, de bâtiment et de manutention, de matériels de motoculture de plaisance, de jardins et d''espaces verts','','','',''),
('RNCP29518','3328','Sport','','','',''),
('RNCP29529','3328','Sport','','','',''),
('RNCP29536','3603','Centres équestres','','','',''),
('RNCP29566','3044','Commerces de gros','','','',''),
('RNCP29567','3044','Commerces de gros','','','',''),
('RNCP29568','3044','Commerces de gros','','','',''),
('RNCP29569','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP29570','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP29571','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP29848','3148','Commerce de gros en bonneterie, lingerie, confection, mercerie, chaussures et négoces connexes','','','',''),
('RNCP29849','3148','Commerce de gros en bonneterie, lingerie, confection, mercerie, chaussures et négoces connexes','','','',''),
('RNCP29850','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP29852','3123','Parfumerie - Esthétique','','','',''),
('RNCP30422','3163','Industrie de la chaussure et des articles chaussants','','','',''),
('RNCP30423','3109','Métallurgie','','','',''),
('RNCP30424','3109','Métallurgie','','','',''),
('RNCP31049','3328','Sport','','','',''),
('RNCP31050','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP31053','','','3225','Personnel des entreprises de restauration de collectivités','',''),
('RNCP31054','3109','Métallurgie','','','',''),
('RNCP31055','3240','Commerce de détail de l''horlogerie-bijouterie','','','',''),
('RNCP31057','3240','Commerce de détail de l''horlogerie-bijouterie','','','',''),
('RNCP31058','3240','Commerce de détail de l''horlogerie-bijouterie','','','',''),
('RNCP31129','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP31313','3152','Horlogerie','','','',''),
('RNCP31314','3152','Horlogerie','','','',''),
('RNCP31315','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31317','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31318','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31326','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31328','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31329','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31330','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31332','3167','Personnel des jeux dans les casinos','','','',''),
('RNCP31333','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31339','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31341','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31342','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31343','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31358','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31359','3328','Sport','','','',''),
('RNCP31363','3243','Poissonnerie (Commerce de détail, gros et demi-gros)','','','',''),
('RNCP31364','3243','Poissonnerie (Commerce de détail, gros et demi-gros)','','','',''),
('RNCP31367','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31368','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31369','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31370','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31371','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31377','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31381','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31383','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31387','3152','Horlogerie','','','',''),
('RNCP31388','','','3275','Espaces, de loisirs, d''attractions et culturels','',''),
('RNCP31389','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP31391','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP31394','3051','Bijouterie, joaillerie, orfèvrerie et activités qui s''y rattachent','','','',''),
('RNCP31395','3110','Cabinets de courtage d''assurances et/ou de réassurances','','','',''),
('RNCP31396','3225','Personnel des entreprises de restauration de collectivités','','','',''),
('RNCP31398','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31401','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31402','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31403','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31404','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31406','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31408','3292','Hôtels, cafés, restaurants (HCR)','','','',''),
('RNCP31411','3297','Chaînes de cafétéria et assimilés','','','',''),
('RNCP31413','3297','Chaînes de cafétéria et assimilés','','','',''),
('RNCP31513','454','Remontées mécaniques et domaines skiables','','','',''),
('RNCP31514','454','Remontées mécaniques et domaines skiables','','','',''),
('RNCP31516','454','Remontées mécaniques et domaines skiables','','','',''),
('RNCP31517','454','Remontées mécaniques et domaines skiables','','','',''),
('RNCP31518','454','Remontées mécaniques et domaines skiables','','','',''),
('RNCP31520','3328','Sport','','','',''),
('RNCP31885','3328','Sport','','','',''),
('RNCP31890','3328','Sport','','','',''),
('RNCP31891','3328','Sport','','','',''),
('RNCP31898','3328','Sport','','','',''),
('RNCP31899','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP31905','3328','Sport','','','',''),
('RNCP31907','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP31909','3328','Sport','','','',''),
('RNCP31910','3108','Industries chimiques et connexes','','','',''),
('RNCP31911','','','3250','Transformation des papiers et cartons et des industries connexes (OETAM)','',''),
('RNCP31915','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP31940','3135','Industries de cartonnage','','','',''),
('RNCP31978','3135','Industries de cartonnage','','','',''),
('RNCP31979','','','3250','Transformation des papiers et cartons et des industries connexes (OETAM)','',''),
('RNCP31981','3242','Production des papiers-cartons et celluloses (OETAM)','','','',''),
('RNCP31989','3134','Notariat','','','',''),
('RNCP32002','3104','Industrie pharmaceutique','','','',''),
('RNCP32008','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP32021','3175','Organismes de tourisme','','','',''),
('RNCP32028','3242','Production des papiers-cartons et celluloses (OETAM)','','','',''),
('RNCP32030','3242','Production des papiers-cartons et celluloses (OETAM)','','','',''),
('RNCP32031','3135','Industries de cartonnage','','','',''),
('RNCP32074','3056','Ameublement','','','',''),
('RNCP32075','3056','Ameublement','','','',''),
('RNCP32076','3056','Ameublement','','','',''),
('RNCP32077','3066','Plasturgie','','','',''),
('RNCP32080','3029','Vins, cidres, jus de fruits, sirops, spiritueux et liqueurs de France','','','',''),
('RNCP32081','3249','Organismes de formation','','','',''),
('RNCP32084','3190','Personnels des sociétés anonymes et fondations d''HLM','','','',''),
('RNCP32085','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP32086','3138','Imprimeries de labeur et industries graphiques','','','',''),
('RNCP32088','','','3106','Industrie textile','',''),
('RNCP32089','3073','Entreprises de la publicité et assimilées','','','',''),
('RNCP32090','3073','Entreprises de la publicité et assimilées','','','',''),
('RNCP32091','3157','Industries de la maroquinerie, articles de voyage, chasse-sellerie, bracelets en cuir','','','',''),
('RNCP32092','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32093','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32094','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32095','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32096','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32097','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32098','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32099','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32100','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32101','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32102','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32103','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32104','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32105','3021','Commerce à  prédominance alimentaire','','','',''),
('RNCP32110','454','Remontées mécaniques et domaines skiables','','','',''),
('RNCP32111','3148','Commerce de gros en bonneterie, lingerie, confection, mercerie, chaussures et négoces connexes','','','',''),
('RNCP32112','3148','Commerce de gros en bonneterie, lingerie, confection, mercerie, chaussures et négoces connexes','','','',''),
('RNCP32113','3247','Activités de production des eaux embouteillées et boissons rafraîchissantes sans alccol et de bière','','','',''),
('RNCP32114','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32115','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32116','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32117','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32118','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32119','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32120','3244','COmmerces de détail des fruits et légumes, épicerie et produits laitiers','','','',''),
('RNCP32161','3155','Fabrication de l''ameublement','','','',''),
('RNCP32164','2717','Entreprises techniques au service de la création et de l''évènement ','','','',''),
('RNCP32211','3328','Sport','','','',''),
('RNCP32223','','','3106','Industrie textile','',''),
('RNCP32225','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','','','',''),
('RNCP32386','3044','Commerces de gros','','','',''),
('RNCP32387','3044','Commerces de gros','','','',''),
('RNCP32388','','','','','3145','Entreprises d''expertises en matière d''évaluations industrielles et commerciales'),
('RNCP32389','3044','Commerces de gros','','','',''),
('RNCP32390','3044','Commerces de gros','','','',''),
('RNCP32391','3044','Commerces de gros','','','',''),
('RNCP34172','3109','Métallurgie','','','',''),
('RNCP34177','3109','Métallurgie','','','',''),
('RNCP34180','3109','Métallurgie','','','',''),
('RNCP34252','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP34263','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP34265','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP34301','3109','Métallurgie','','','',''),
('RNCP34308','3109','Métallurgie','','','',''),
('RNCP34347','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP34366','3018','Bureaux d''études techniques, cabinets d''ingénieurs-conseils et sociétés de conseil','','','',''),
('RNCP34367','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP34370','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','3005T2','Ouvriers des entreprises de travaux publics','',''),
('RNCP34371','3107','Bâtiment et travaux publics','3005T2','Ouvriers des entreprises de travaux publics','',''),
('RNCP34400','3106','Industrie textile','','','',''),
('RNCP34472','3109','Métallurgie','','','',''),
('RNCP34480','3109','Métallurgie','','','',''),
('RNCP34486','3196','Entreprises de prévention et de sécurité','','','',''),
('RNCP34487','3196','Entreprises de prévention et de sécurité','','','',''),
('RNCP34514','3328','Sport','','','',''),
('RNCP34515','3328','Sport','','','',''),
('RNCP34528','3328','Sport','','','',''),
('RNCP34531','3301','Personnel des prestataires de services dans le domaine du secteur tertiaire','','','',''),
('RNCP34572','3109','Métallurgie','','','',''),
('RNCP34575','3109','Métallurgie','','','',''),
('RNCP34596','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP34597','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP34598','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP34713','3109','Métallurgie','','','',''),
('RNCP34733','3328','Sport','','','',''),
('RNCP34763','3161','Personnel des banques','','','',''),
('RNCP34935','3606','Entreprises d''accouvage et de sélection','','','',''),
('RNCP34942','3606','Entreprises d''accouvage et de sélection','','','',''),
('RNCP34973','3328','Sport','','','',''),
('RNCP34985','3109','Métallurgie','','','',''),
('RNCP34989','3109','Métallurgie','3106','Industrie textile','',''),
('RNCP35002','3604','Caves coopératives vinicoles et leurs unions','','','',''),
('RNCP35012','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP35014','3328','Sport','','','',''),
('RNCP35064','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP35092','3109','Métallurgie','','','',''),
('RNCP35158','3328','Sport','','','',''),
('RNCP35171','3109','Métallurgie','','','',''),
('RNCP35216','3109','Métallurgie','','','',''),
('RNCP35279','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP35281','3109','Métallurgie','','','',''),
('RNCP35282','3109','Métallurgie','','','',''),
('RNCP35411','3104','Industrie pharmaceutique','','','',''),
('RNCP35412','3104','Industrie pharmaceutique','','','',''),
('RNCP35413','3271','Hôtellerie de plein air','','','',''),
('RNCP35426','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP35449','3058','Industrie des cuirs et peaux','','','',''),
('RNCP35531','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP35556','2717','Entreprises techniques au service de la création et de l''évènement ','','','',''),
('RNCP35586','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','3109','Métallurgie'),
('RNCP35603','3111','Abattoirs, ateliers de découpe et centres de conditionnement de volailles','','','',''),
('RNCP35618','3617','Entreprises du paysage (Salariés non cadres)','','','',''),
('RNCP35654','3005T2','Ouvriers des entreprises de travaux publics','3005T1','Entreprises de travaux publics','',''),
('RNCP35665','3131','Entreprises de commerce, de location et de réparation de tracteurs, machines et matériels agricoles, de matériels de travaux publics, de bâtiment et de manutention, de matériels de motoculture de plaisance, de jardins et d''espaces verts','','','',''),
('RNCP35666','3131','Entreprises de commerce, de location et de réparation de tracteurs, machines et matériels agricoles, de matériels de travaux publics, de bâtiment et de manutention, de matériels de motoculture de plaisance, de jardins et d''espaces verts','','','',''),
('RNCP35668','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP35677','2642','Production audiovisuelle ','','','',''),
('RNCP35731','3122','Téléphériques et engins de remontées mécaniques','','','',''),
('RNCP35732','3122','Téléphériques et engins de remontées mécaniques','','','',''),
('RNCP35736','3122','Téléphériques et engins de remontées mécaniques','','','',''),
('RNCP35737','3122','Téléphériques et engins de remontées mécaniques','','','',''),
('RNCP35738','3122','Téléphériques et engins de remontées mécaniques','','','',''),
('RNCP35762','3124','Industrie laitière','3608','Coopératives agricoles laitières','',''),
('RNCP35763','3124','Industrie laitière','3608','Coopératives agricoles laitières','',''),
('RNCP35764','3124','Industrie laitière','3608','Coopératives agricoles laitières','',''),
('RNCP35765','3124','Industrie laitière','3608','Coopératives agricoles laitières','',''),
('RNCP35858','3104','Industrie pharmaceutique','','','',''),
('RNCP35868','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP35885','3109','Métallurgie','','','',''),
('RNCP35898','3328','Sport','','','',''),
('RNCP35956','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP35984','3300','Mutualité','','','',''),
('RNCP35985','3109','Métallurgie','','','',''),
('RNCP35986','3300','Mutualité','','','',''),
('RNCP35988','3109','Métallurgie','','','',''),
('RNCP36019','3109','Métallurgie','','','',''),
('RNCP36023','3144','Gardiens, concierges et employés d''immeubles','','','',''),
('RNCP36027','3109','Métallurgie','','','',''),
('RNCP36028','3109','Métallurgie','','','',''),
('RNCP36029','3109','Métallurgie','','','',''),
('RNCP36030','3300','Mutualité','','','',''),
('RNCP36086','3109','Métallurgie','','','',''),
('RNCP36138','3109','Métallurgie','','','',''),
('RNCP36140','3265','Sociétés d''assurances','3267','Inspection d''assurance','',''),
('RNCP36152','3124','Industrie laitière','3608','Coopératives agricoles laitières','',''),
('RNCP36154','3328','Sport','','','',''),
('RNCP36198','3109','Métallurgie','','','',''),
('RNCP36199','3328','Sport','','','',''),
('RNCP36200','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP36201','3109','Métallurgie','','','',''),
('RNCP36206','3058','Industrie des cuirs et peaux','','','',''),
('RNCP36221','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP36223','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP36230','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','',''),
('RNCP36274','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP36275','3109','Métallurgie','','','',''),
('RNCP36276','3109','Métallurgie','','','',''),
('RNCP36278','3328','Sport','','','',''),
('RNCP36280','3109','Métallurgie','','','',''),
('RNCP36283','3109','Métallurgie','','','',''),
('RNCP36299','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP36302','3109','Métallurgie','','','',''),
('RNCP36303','3109','Métallurgie','','','',''),
('RNCP36308','3109','Métallurgie','','','',''),
('RNCP36311','3109','Métallurgie','','','',''),
('RNCP36313','3260','Entreprises de désinfection, désinsectisation, dératisation (3 D)','','','',''),
('RNCP36357','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP36358','3168','Personnel des cabinets médicaux','','','',''),
('RNCP36360','3116','Etablissements et services pour personnes inadaptées et handicapées','3198','Etablissements privés d''hospitalisation, de soins, de cure et de garde à  but non lucratif(FEHAP)','',''),
('RNCP36362','3109','Métallurgie','','','',''),
('RNCP36363','3109','Métallurgie','','','',''),
('RNCP36376','3109','Métallurgie','','','',''),
('RNCP36377','3109','Métallurgie','','','',''),
('RNCP36402','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP36409','3328','Sport','','','',''),
('RNCP36449','3256','Mareyeurs-expéditeurs','','','',''),
('RNCP36451','3109','Métallurgie','','','',''),
('RNCP36452','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP36453','3109','Métallurgie','','','',''),
('RNCP36456','3300','Mutualité','','','',''),
('RNCP36457','3300','Mutualité','','','',''),
('RNCP36458','3328','Sport','','','',''),
('RNCP36474','3109','Métallurgie','','','',''),
('RNCP36477','3157','Industries de la maroquinerie, articles de voyage, chasse-sellerie, bracelets en cuir','','','',''),
('RNCP36481','3246','Animation socioculturelle','','','',''),
('RNCP36499','3228','Industries et commerces de la récupération','','','',''),
('RNCP36506','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP36508','3066','Plasturgie','','','',''),
('RNCP36509','3066','Plasturgie','','','',''),
('RNCP36510','3066','Plasturgie','','','',''),
('RNCP36585','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP36587','3109','Métallurgie','','','',''),
('RNCP36597','3101','Boucherie, boucherie-charcuterie et boucherie hippophagique.Commerces de détail de boucherie','','','',''),
('RNCP36614','3109','Métallurgie','','','',''),
('RNCP36626','3302','Entreprises des services d''eau et d''assainissement','','','',''),
('RNCP36635','3228','Industries et commerces de la récupération','','','',''),
('RNCP36656','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP36661','3328','Sport','','','',''),
('RNCP36691','3328','Sport','','','',''),
('RNCP36712','3081','Industries de carrières et de matériaux (UNICEM)','','','',''),
('RNCP36718','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)','','','',''),
('RNCP36722','3005T2','Ouvriers des entreprises de travaux publics','','','',''),
('RNCP36736','3109','Métallurgie','','','',''),
('RNCP36737','3109','Métallurgie','','','',''),
('RNCP36742','3105','Régies de quartier','','','',''),
('RNCP36869','3109','Métallurgie','','','',''),
('RNCP36870','3109','Métallurgie','','','',''),
('RNCP36872','3109','Métallurgie','','','',''),
('RNCP36913','3193','Bâtiment (Ouvriers)(Entreprises occupant jusqu''à  10 salariés)','3258','Entreprises de bâtiment occupant plus de dix salariés (Ouvriers)','',''),
('RNCP36915','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP36994','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP36996','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','3092','Industries alimentaires diverses'),
('RNCP37002','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP37009','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP37014','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP37015','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP37016','3060','Meunerie','','','',''),
('RNCP37017','3066','Plasturgie','','','',''),
('RNCP37018','3328','Sport','','','',''),
('RNCP37039','3328','Sport','','','',''),
('RNCP37049','3109','Métallurgie','','','',''),
('RNCP37070','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP37071','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP37094','3161','Personnel des banques','','','',''),
('RNCP37132','3179','Entreprises de l''industrie et des commerces en gros des viandes','','','',''),
('RNCP37134','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP37148','3603','Centres équestres','','','',''),
('RNCP37149','3090','Immobilier (Administrateurs de biens, sociétés immobilières, agents immobiliers)','','','',''),
('RNCP37150','3109','Métallurgie','','','',''),
('RNCP37165','3109','Métallurgie','','','',''),
('RNCP37171','3122','Téléphériques et engins de remontées mécaniques','','','',''),
('RNCP37174','3101','Boucherie, boucherie-charcuterie et boucherie hippophagique.Commerces de détail de boucherie','','','',''),
('RNCP37186','3034','Services de l''automobile (Commerce et réparation de l''automobile, du cycle et du motocycle, activités connexe, contrôle technique automobile, formation des conducteurs)','','','',''),
('RNCP37268','3109','Métallurgie','','','',''),
('RNCP37281','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP37282','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP37283','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP37284','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RNCP37285','3154','Négoce des matériaux de construction (OETAM et cadres)','','','',''),
('RS5478','3107','Bâtiment et travaux publics','3032','Bâtiment de la région parisienne (Ouvriers, employés, techniciens et agents de maîtrise, ingénieurs, assimilés cadres)','3002','Bâtiment (Employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres)'),
('RS6117','3117','Boulangerie-pâtisserie (Entreprises artisanales)','','','',''),
('RS6174','3107','Bâtiment et travaux publics','','','',''),
('RS6214','3196','Entreprises de prévention et de sécurité','','','','')
